# Generated by Django 2.1.7 on 2019-03-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='good_with_cats',
            field=models.BooleanField(default=False, verbose_name='Good with cats'),
        ),
        migrations.AddField(
            model_name='dog',
            name='good_with_dogs',
            field=models.BooleanField(default=False, verbose_name='Good with other dogs'),
        ),
        migrations.AddField(
            model_name='dog',
            name='good_with_kids',
            field=models.BooleanField(default=False, verbose_name='Good with kids'),
        ),
    ]
