# Generated by Django 2.1.7 on 2019-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190307_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='energy_level',
            field=models.PositiveIntegerField(choices=[(1, 'Easygoing'), (3, 'Playful'), (5, 'Energetic')], default=5),
            preserve_default=False,
        ),
    ]
