# Generated by Django 2.1.7 on 2019-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='dogs',
            field=models.ManyToManyField(related_name='events', to='core.Dog'),
        ),
    ]
