# Generated by Django 2.1.7 on 2019-03-13 14:38

import csv
import os.path

from django.db import migrations
from django.conf import settings
from django.core.files import File


def load_dog_data(apps, schema_editor):
    """
    Read a CSV file full of dogs and insert them into the database.
    """
    Dog = apps.get_model('core', 'Dog')
    DogBreed = apps.get_model('core', 'DogBreed')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'dogs.csv')
    Dog.objects.all().delete()
    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:

            if not row['breed'] or row['breed'] == 'Unknown':
                breed = None
            else:
                breed, _ = DogBreed.objects.get_or_create(name=row['breed'])

            dog = Dog(
                name=row['name'],
                size=row['size'],
                age=row['age'],
                breed=breed,
                description=row['description'],
                good_with_kids=row['good_with_kids'],
                good_with_dogs=row['good_with_dogs'],
                good_with_cats=row['good_with_cats'],
                energy_level=3)
            dog.picture.save(
                row['image'],
                File(open(os.path.join(datapath, row['image']), 'rb')))

            dog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190313_1038'),
    ]

    operations = [migrations.RunPython(load_dog_data)]
