# Generated by Django 2.1.7 on 2019-03-13 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20190313_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='applicant_name',
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
